export const enContent = {
  common: {
    backToHome: 'Back to Home',
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    save: 'Save',
    saving: 'Saving...',
  },
  login: {
    title: 'Log in',
    subtitle: 'Continue to your workspace overview',
    email: 'Email',
    password: 'Password',
    submit: 'Log in',
    submitting: 'Logging in...',
    loginFailed: 'Login failed',
    networkError: 'Network error',
    brandSub: 'Workspace for high velocity teams',
    headline: 'Plan smarter. Deliver faster.',
    lead: 'Bring goals, tasks and execution into one clear flow for your team.',
    kpiActiveProjects: 'Active Projects',
    kpiTasksClosed: 'Tasks Closed',
    kpiCycleTime: 'Cycle Time',
  },
  home: {
    loading: 'Building your workspace...',
    projectFallback: 'Company Event',
    guest: 'Guest',
    signedIn: 'Signed in',
    sidebar: {
      brandSub: 'Work faster, stay aligned',
      workspace: 'Workspace',
      home: 'Home',
      notifications: 'Notifications',
      goals: 'Goals',
      archive: 'Archive',
      spaces: 'Spaces',
      noSpaces: 'No spaces found',
      newSpace: 'New Space',
    },
    topbar: {
      list: 'List',
      board: 'Board',
      box: 'Box',
      spaceSettings: 'Space settings',
      logout: 'Logout',
    },
    quickActions: {
      newTask: 'New Task',
      searchPlaceholder: 'Search tasks, meta, section or assignee',
    },
    overview: {
      openTasks: 'Open Tasks',
      openTasksSynced: (count: number) => `${count} tasks synced from /api/task.`,
      noTasksInDb: 'No tasks in DB yet.',
      users: 'Users',
      usersConnectedEmails: (count: number) => `${count} users have connected emails.`,
      dueThisWeek: 'Due This Week',
      busiestLane: (section: string) => `${section} lane is the busiest.`,
      noTaskActivity: 'No task activity yet.',
    },
    task: {
      taskLabel: 'Task',
      assigneeLabel: 'Assignee',
      done: 'Done',
      duePrefix: 'Due',
      archivedPrefix: 'Archived',
      priorityPrefix: 'Priority',
      unassigned: 'Unassigned',
      high: 'High',
      normal: 'Normal',
      low: 'Low',
    },
    createModal: {
      title: 'Create Task',
      subtitle: 'Fill in details and add to board',
      taskTitlePlaceholder: 'Task title',
      descriptionPlaceholder: 'Task description (Markdown supported)',
      colorLabel: 'Task color',
      create: 'Create Task',
      creating: 'Creating...',
    },
    editModal: {
      title: 'Task',
      subtitle: 'Update details and save changes',
      taskTitlePlaceholder: 'Task title',
      descriptionPlaceholder: 'Task description (Markdown supported)',
      colorLabel: 'Task color',
      archiveTask: 'Archive task',
      deleteTask: 'Delete task',
      saveChanges: 'Save changes',
      saving: 'Saving...',
      deleteConfirmTitle: 'Delete task?',
      deleteConfirmSubtitle: 'This action cannot be undone.',
      deleting: 'Deleting...',
      confirmDelete: 'Yes, delete',
    },
    spaceSettings: {
      title: 'Space Settings',
      subtitle: 'Manage custom task columns for this space',
      spaceNamePlaceholder: 'Space name',
      addColumnPlaceholder: 'Add new column (e.g. QA, Done, Blocked)',
      add: 'Add',
      colorForSection: (section: string) => `Color for ${section}`,
      saveSettings: 'Save settings',
    },
    searchResult: (shown: number, total: number, query: string) =>
      `Showing ${shown} of ${total} tasks for \"${query}\"`,
    workspaceSubConnected: (city: string) =>
      `${city} workspace connected to live data.`,
    workspaceSubFallback:
      'Campaign planning across review, approval and launch.',
    errors: {
      adminOnlySpaceSettings: 'Only admins can update space settings.',
      selectSpaceFirst: 'Select a space before saving settings.',
      spaceNameRequired: 'Space name is required.',
      saveSpaceSettingsFailed: 'Could not save space settings.',
      selectOrganizationFirst: 'Select an organization first.',
      createSpaceFailed: 'Could not create a new space.',
    },
  },
  goals: {
    loading: 'Loading goals...',
    title: 'Goals',
    subtitle: 'Track outcomes with automatic progress from linked tasks.',
    form: {
      createTitle: 'Create Goal',
      editTitle: 'Edit Goal',
      help: 'Link tasks to calculate progress automatically',
      titleLabel: 'Title',
      titlePlaceholder: 'Launch Q2 onboarding',
      targetDateLabel: 'Target Date',
      spaceLabel: 'Space',
      noSpace: 'No specific space',
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Reduce cycle time and improve quality',
      progressOverride: 'Progress Override',
      useManualProgress: 'Use manual progress',
      autoProgressActive: 'Auto progress from linked tasks is active.',
      linkedTasks: 'Linked Tasks',
      noTasksForFilter: 'No tasks available for this filter.',
      searchTaskPlaceholder: 'Search task by title or section',
      allVisibleTasksLinked: 'All visible tasks are linked',
      noTasksMatchSearch: 'No tasks match search',
      chooseTaskToLink: 'Choose task to link',
      link: 'Link',
      noLinkedTasks: 'No linked tasks yet.',
      cancelEdit: 'Cancel Edit',
      createGoal: 'Create Goal',
      saveGoal: 'Save Goal',
    },
    list: {
      title: 'Goal List',
      subtitle: 'Progress and risk overview',
      noGoals: 'No goals yet.',
      progressLabel: 'Progress',
      manual: 'manual',
      auto: 'auto',
      linkedTasks: 'Linked tasks',
      target: 'Target',
      atRisk: 'At risk',
      edit: 'Edit',
      delete: 'Delete',
    },
  },
  archive: {
    loading: 'Loading archive...',
    title: 'Archive',
    subtitleWithOrg: (orgName: string) => `Archived tasks for ${orgName}`,
    subtitleFallback: 'Archived tasks across your workspace',
    noTasks: 'No archived tasks found.',
    restore: 'Restore',
    working: 'Working...',
  },
  settings: {
    loading: 'Loading settings...',
    title: 'Settings',
    subtitle: 'Manage team access, roles and profile details.',
    members: {
      title: 'Team Members',
      subtitle: 'View and manage workspace access',
    },
    organizationFallback: 'No organization',
    adminUsers: {
      title: 'Admin: Users',
      subtitle: 'Create users and adjust roles',
      newUserName: 'New user name',
      newUserEmail: 'New user email',
      tempPassword: 'Temporary password',
      role: 'Role',
      optional: 'Optional',
      passwordHint: 'At least 6 characters',
      create: 'Create User',
      creating: 'Creating...',
    },
    adminSpaceMembers: {
      title: 'Admin: Space Members',
      subtitle: 'Manage memberships both by space and by user',
      user: 'User',
      spacesForUser: 'Spaces for user',
      saveUserSpaces: 'Save User Spaces',
      savingUserSpaces: 'Saving...',
      noSpaces: 'No spaces',
    },
    adminOrganization: {
      title: 'Admin: Organization',
      subtitle: 'Manage organization name',
      organizationName: 'Organization Name',
      organizationNamePlaceholder: 'Organization name',
      saveOrganization: 'Save Organization',
      savingOrganization: 'Saving...',
    },
    profile: {
      title: 'Profile',
      subtitle: 'Update your personal preferences',
      labels: {
        name: 'Name',
        email: 'Email',
        role: 'Role',
        language: 'Language',
        newPassword: 'New Password',
        organization: 'Organization',
      },
      placeholders: {
        name: 'Your name',
        email: 'you@company.com',
        newPassword: 'Leave blank to keep current password',
      },
      languageOptions: {
        sv: 'Svenska',
        en: 'English',
      },
      passwordHelp: 'Set a new password only if needed.',
      actions: {
        cancel: 'Cancel',
        save: 'Save Profile',
        saving: 'Saving...',
      },
    },
  },
} as const
