export const svContent = {
  common: {
    backToHome: 'Tillbaka till startsidan',
    cancel: 'Avbryt',
    close: 'Stäng',
    delete: 'Ta bort',
    save: 'Spara',
    saving: 'Sparar...',
  },
  login: {
    title: 'Logga in',
    subtitle: 'Fortsätt till din workspace-översikt',
    email: 'E-post',
    password: 'Lösenord',
    submit: 'Logga in',
    submitting: 'Loggar in...',
    loginFailed: 'Inloggning misslyckades',
    networkError: 'Nätverksfel',
    brandSub: 'Workspace för team med hög leveransfart',
    headline: 'Planera smartare. Leverera snabbare.',
    lead: 'Samla goals, tasks och execution i ett tydligt flöde för hela teamet.',
    kpiActiveProjects: 'Aktiva projekt',
    kpiTasksClosed: 'Avslutade tasks',
    kpiCycleTime: 'Ledtid',
  },
  home: {
    loading: 'Bygger din workspace...',
    projectFallback: 'Företagsevent',
    guest: 'Gäst',
    signedIn: 'Inloggad',
    sidebar: {
      brandSub: 'Jobba snabbare, håll teamet synkat',
      workspace: 'Workspace',
      home: 'Hem',
      log: 'Logg',
      goals: 'Mål',
      archive: 'Arkiv',
      spaces: 'Spaces',
      noSpaces: 'Inga spaces hittades',
      newSpace: 'Nytt space',
      darkMode: 'Morkt lage',
      lightMode: 'Ljust lage',
      logout: 'Logga ut',
    },
    topbar: {
      list: 'Lista',
      board: 'Board',
      box: 'Box',
      spaceSettings: 'Space-inställningar',
      logout: 'Logga ut',
    },
    quickActions: {
      newTask: 'Ny task',
      searchPlaceholder: 'Sök tasks, metadata, sektion eller ansvarig',
    },
    overview: {
      openTasks: 'Öppna tasks',
      openTasksSynced: (count: number) =>
        `${count} tasks synkade från /api/task.`,
      noTasksInDb: 'Inga tasks i databasen än.',
      users: 'Användare',
      usersConnectedEmails: (count: number) =>
        `${count} användare har kopplad e-post.`,
      dueThisWeek: 'Förfaller den här veckan',
      busiestLane: (section: string) => `${section}-kolumnen är mest belastad.`,
      noTaskActivity: 'Ingen task-aktivitet än.',
    },
    task: {
      taskLabel: 'Task',
      assigneeLabel: 'Ansvarig',
      done: 'Klar',
      duePrefix: 'Förfaller',
      archivedPrefix: 'Arkiverad',
      priorityPrefix: 'Prioritet',
      unassigned: 'Ej tilldelad',
      high: 'Hög',
      normal: 'Normal',
      low: 'Låg',
    },
    createModal: {
      title: 'Skapa task',
      subtitle: 'Fyll i detaljer och lägg till i board',
      taskTitlePlaceholder: 'Task-titel',
      descriptionPlaceholder: 'Task-beskrivning (Markdown stöds)',
      colorLabel: 'Task-färg',
      create: 'Skapa task',
      creating: 'Skapar...',
    },
    editModal: {
      title: 'Task',
      subtitle: 'Uppdatera detaljer och spara ändringar',
      taskTitlePlaceholder: 'Task-titel',
      descriptionPlaceholder: 'Task-beskrivning (Markdown stöds)',
      colorLabel: 'Task-färg',
      archiveTask: 'Arkivera task',
      deleteTask: 'Ta bort task',
      saveChanges: 'Spara ändringar',
      saving: 'Sparar...',
      deleteConfirmTitle: 'Ta bort task?',
      deleteConfirmSubtitle: 'Den här handlingen kan inte ångras.',
      deleting: 'Tar bort...',
      confirmDelete: 'Ja, ta bort',
    },
    spaceSettings: {
      title: 'Space-inställningar',
      subtitle: 'Hantera anpassade task-kolumner för detta space',
      spaceNamePlaceholder: 'Space-namn',
      addColumnPlaceholder: 'Lägg till ny kolumn (t.ex. QA, Klar, Blockerad)',
      add: 'Lägg till',
      colorForSection: (section: string) => `Färg för ${section}`,
      saveSettings: 'Spara inställningar',
    },
    searchResult: (shown: number, total: number, query: string) =>
      `Visar ${shown} av ${total} tasks för \"${query}\"`,
    workspaceSubConnected: (city: string) =>
      `${city}-workspace är kopplad till live-data.`,
    workspaceSubFallback: 'Planering över review, godkännande och lansering.',
    errors: {
      adminOnlySpaceSettings: 'Bara admins kan uppdatera space-inställningar.',
      selectSpaceFirst: 'Välj ett space innan du sparar inställningar.',
      spaceNameRequired: 'Space-namn är obligatoriskt.',
      saveSpaceSettingsFailed: 'Kunde inte spara space-inställningar.',
      selectOrganizationFirst: 'Välj en organization först.',
      createSpaceFailed: 'Kunde inte skapa nytt space.',
    },
  },
  goals: {
    loading: 'Laddar mål...',
    title: 'Mål',
    subtitle: 'Följ utfall med automatisk progress från länkade tasks.',
    form: {
      createTitle: 'Skapa mål',
      editTitle: 'Redigera mål',
      help: 'Länka tasks för att beräkna progress automatiskt',
      titleLabel: 'Titel',
      titlePlaceholder: 'Lansera onboarding Q2',
      targetDateLabel: 'Mål-datum',
      spaceLabel: 'Space',
      noSpace: 'Inget specifikt space',
      descriptionLabel: 'Beskrivning',
      descriptionPlaceholder: 'Minska ledtid och öka kvalitet',
      progressOverride: 'Progress-overstyrning',
      useManualProgress: 'Använd manuell progress',
      autoProgressActive: 'Automatisk progress från länkade tasks är aktiv.',
      linkedTasks: 'Länkade tasks',
      noTasksForFilter: 'Inga tasks tillgängliga för detta filter.',
      searchTaskPlaceholder: 'Sök task på titel eller sektion',
      allVisibleTasksLinked: 'Alla synliga tasks är länkade',
      noTasksMatchSearch: 'Inga tasks matchar sökningen',
      chooseTaskToLink: 'Välj task att länka',
      link: 'Länka',
      noLinkedTasks: 'Inga länkade tasks än.',
      cancelEdit: 'Avbryt redigering',
      createGoal: 'Skapa mål',
      saveGoal: 'Spara mål',
    },
    list: {
      title: 'Mållista',
      subtitle: 'Översikt av progress och risk',
      noGoals: 'Inga mål än.',
      progressLabel: 'Progress',
      manual: 'manuell',
      auto: 'automatisk',
      linkedTasks: 'Länkade tasks',
      target: 'Mål',
      atRisk: 'Risk',
      edit: 'Redigera',
      delete: 'Ta bort',
    },
  },
  archive: {
    loading: 'Laddar arkiv...',
    title: 'Arkiv',
    subtitleWithOrg: (orgName: string) => `Arkiverade tasks for ${orgName}`,
    subtitleFallback: 'Arkiverade tasks i hela din workspace',
    noTasks: 'Inga arkiverade tasks hittades.',
    restore: 'Återställ',
    working: 'Arbetar...',
  },
  log: {
    loading: 'Laddar notiser...',
    title: 'Logg',
    subtitle: 'Live-logg av andringar i din workspace.',
    empty: 'Inga notiser an.',
    actions: {
      clear: 'Rensa',
      pause: 'Pausa live',
      resume: 'Fortsatt live',
    },
    eventTypes: {
      connected: 'Ansluten till live-flode',
      taskChanged: 'Task uppdaterad',
      goalChanged: 'Mal uppdaterat',
      spaceChanged: 'Space uppdaterat',
      userChanged: 'Anvandare uppdaterad',
      organizationChanged: 'Organisation uppdaterad',
      unknown: 'Okand andring',
    },
    taskActions: {
      created: 'Task skapad',
      updated: 'Task uppdaterad',
      moved: 'Task flyttad',
      deleted: 'Task borttagen',
    },
  },
  settings: {
    loading: 'Laddar inställningar...',
    title: 'Inställningar',
    subtitle: 'Hantera team, roller och profilinformation.',
    members: {
      title: 'Team Members',
      subtitle: 'View and manage workspace access',
    },
    organizationFallback: 'Ingen organisation',
    adminUsers: {
      title: 'Admin: Användare',
      subtitle: 'Skapa användare och uppdatera roller',
      newUserName: 'Namn på ny användare',
      newUserEmail: 'E-post för ny användare',
      tempPassword: 'Tillfälligt lösenord',
      role: 'Roll',
      optional: 'Valfritt',
      passwordHint: 'Minst 6 tecken',
      create: 'Skapa användare',
      creating: 'Skapar...',
    },
    adminSpaceMembers: {
      title: 'Admin: Space-medlemmar',
      subtitle: 'Hantera medlemskap per space och per användare',
      user: 'Användare',
      spacesForUser: 'Spaces för användare',
      saveUserSpaces: 'Spara användarens spaces',
      savingUserSpaces: 'Sparar...',
      noSpaces: 'Inga spaces',
    },
    adminOrganization: {
      title: 'Admin: Organisation',
      subtitle: 'Hantera organisationsnamn',
      organizationName: 'Organisationsnamn',
      organizationNamePlaceholder: 'Organisationsnamn',
      saveOrganization: 'Spara organisation',
      savingOrganization: 'Sparar...',
    },
    profile: {
      title: 'Profil',
      subtitle: 'Uppdatera dina personliga inställningar',
      labels: {
        name: 'Namn',
        email: 'E-post',
        role: 'Roll',
        language: 'Språk',
        newPassword: 'Nytt lösenord',
        organization: 'Organisation',
      },
      placeholders: {
        name: 'Ditt namn',
        email: 'you@company.com',
        newPassword: 'Lämna tomt för att behålla nuvarande lösenord',
      },
      languageOptions: {
        sv: 'Svenska',
        en: 'Engelska',
      },
      passwordHelp: 'Ange ett nytt lösenord endast vid behov.',
      actions: {
        cancel: 'Avbryt',
        save: 'Spara profil',
        saving: 'Sparar...',
      },
    },
  },
} as const
